# Site settings
title: Mundim da Educação
description: Plataforma de cursos
baseurl: "/schedule" # the subpath of your site, e.g. /blog
url: "https://leandromundim.com" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Leandro Mundim
user_description: Nerd, boleiro e empreendedor
user_title: compartilhando conhecimento
email: leandroresendemundim@gmail.com
twitter_username: drmundim
github_username:  drmundim
gplus_username:  +LeandroResendeMundim
disqus_username: drmundim

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/
